const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';
const IS_LOGIN_FORM = 'IS_LOGIN_FORM';
const CHANGE_INFO_USER = 'CHANGE_INFO_USER';
const GET_METHODICS_USER = 'GET_METHODICS_USER';
const PATIENT_DATA = 'PATIENT_DATA';
const SWITCH_CURRENT_EMAIL = 'SWITCH_CURRENT_EMAIL';
const ANALYZES_DATA = 'ANALYZES_DATA';

module.exports = {
  LOG_IN,
  LOG_OUT,
  IS_LOGIN_FORM,
  GET_METHODICS_USER,
  PATIENT_DATA,
  SWITCH_CURRENT_EMAIL,
  CHANGE_INFO_USER,
  ANALYZES_DATA,
};
